version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: kekslop/test_skanestas:latest
    restart: always
    depends_on:
      - db
    links:
      - db
    networks:
        vpc:
         ipv4_address: 10.5.0.2

  db:
    image: clickhouse/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
        - db:/var/lib/clickhouse
        #- ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ulimits:
      nproc: 65535
      nofile:
        soft: "262144"
        hard: "262144"
    networks:
        vpc:
         ipv4_address: 10.5.0.3

networks:
  vpc:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

volumes:
  db:
